<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UsoCfdiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::table('cat_uso_cfdi')->insert([
            [
                'clave' => 'G01',
                'descripcion' => 'Adquisición de mercancias',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'G02',
                'descripcion' => 'Devolución, descuento o bonificación',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625,626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'G03',
                'descripcion' => 'Gastos en general',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I01',
                'descripcion' => 'Construcciones',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I02',
                'descripcion' => 'Mobilario y equipo de oficina por inversiones.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I03',
                'descripcion' => 'Equipo de transporte.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I04',
                'descripcion' => 'Equipo de computo y accesorios.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I05',
                'descripcion' => 'Dados, troqueles, moldes, matrices y herramental.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I06',
                'descripcion' => 'Comunicaciones telefónicas.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I07',
                'descripcion' => 'Comunicaciones satelitales.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'I08',
                'descripcion' => 'Otra maquinaria y equipo.',
                'persona_fisica' => 1,
                'persona_moral' => 1,
                'regimen_fiscal_receptor' => '601, 603, 606, 612, 620, 621, 622, 623, 624, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D01',
                'descripcion' => 'Honorarios médicos, dentales y gastos hospitalarios.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D02',
                'descripcion' => 'Gastos médicos por incapacidad o discapacidad.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D03',
                'descripcion' => 'Gastos funerarios.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D04',
                'descripcion' => 'Donativos.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D05',
                'descripcion' => 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D06',
                'descripcion' => 'Aportaciones voluntarias al SAR.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D07',
                'descripcion' => 'Primas por seguros de gastos médicos.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D08',
                'descripcion' => 'Gastos de transportación escolar obligatoria.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D09',
                'descripcion' => 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'D10',
                'descripcion' => 'Pagos por servicios educativos (colegiaturas).',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '605, 606, 608, 611, 612, 614, 607, 615, 625',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'clave' => 'S01',
                'descripcion' => 'Sin efectos fiscales.',
                'persona_fisica' => 1,
                'persona_moral' => 0,
                'regimen_fiscal_receptor' => '601, 603, 605, 606, 608, 610, 611, 612, 614, 616, 620, 621, 622, 623, 624, 607, 615, 625, 626',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
